### ISSUE TITLE
Ready for a stable release?

### ISSUE THREAD

**Issue by roborourke** [PHPCSStandards/PHPCSExtra#91] opened 2021-05-17 11:40 UTC
Hey, there has been an Alpha release available since Jun last year. Since there are 100+ average installs per day from packagist.org would it be time to cut a 1.0.0 stable release?

We have a case where setting the `minimum-stability` to `dev` or `alpha` in a project `composer.json` is undesirable, hence the question.

Thanks for putting this package together!

**Comment by jrfnl** [comment] 2021-05-17 12:14
Hi @roborourke Yes, yes, 100% yes.

The problem is just that for PHPCSExtra to get a stable release, the underlying [PHPCSUtils](https://github.com/PHPCSStandards/PHPCSUtils) dependency needs a stable release and unfortunately PHP 8.0 threw a massive spanner in the wheels for that.

While PHP 8.0 isn't such a big deal for well coded, well tested projects (which these are), for any project which is based on the PHP `Tokenizer` extension, PHP 8.0 introduced more changes than all the PHP 7.x releases combined and they all have to be dealt with and polyfilled in both PHPCS as well as PHPCSUtils.

I've spend a huge amount of time over the past year on making PHP_CodeSniffer itself compatible with PHP 8.0 and while the [PHPCS 3.6.0 release](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.6.0) is _mostly_ compatible, we're still not there yet - most notably see https://github.com/squizlabs/PHP_CodeSniffer/issues/3298 (with open PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3320) and https://github.com/squizlabs/PHP_CodeSniffer/issues/3336. 

For the most part, PHPCSUtils has been kept up to date with what I did for PHPCS, though there are some things I still need to backport/deal with in PHPCSUtils, like `match` expressions, attributes and reserved keywords which aren't actually reserved keywords.
I'm still undecided whether the support for these things will make it into the 1.0.0 release, but everything what's already in PHPCSUtils should - at the least - not throw errors or false positives for these.

I've been focusing on PHPCSUtils for the past few weeks and am hoping to get alpha4 tagged this week and beta 1/RC in a couple of weeks.

Once PHPCSUtils `1.0.0` is tagged, PHPCSExtra `1.0.0` will follow very quickly.

Also see an extensive explanation about the different layers of compatibility for PHPCS based projects here: https://github.com/PHPCompatibility/PHPCompatibility/issues/1236#issuecomment-708443602 and this rant of mine about PHP 8.0: https://24daysindecember.net/2020/12/21/a-perfect-storm/

**Comment by roborourke** [comment] 2021-05-17 12:42
Wow! Sounds like it's been a nightmare but good news that you're finally in a position to make progress on this front. Thanks so much for the comprehensive answer and links for further reading - feel free to close this issue out, I'll keep an eye on any developments.

**Comment by jrfnl** [comment] 2021-05-18 22:07
@roborourke FYI: I'll leave this issue open for the time being so it's easy to find for other people who may have the same question. Will close it nearer to the release.

**Comment by jrfnl** [comment] 2022-10-27 06:41
FYI:

Well, those "couple of weeks" turned out to be a little too optimistic... match, enum and even more so attributes really turned out to be a lot more problematic than I hoped.

But... after consultation with the main dependencies of PHPCSUtils, support for PHPCS < 3.7.1 has now (finally) been dropped, which solves the problem. This means Utils 1.0.0-alpha4 has been tagged, Extra 1.0.0-alpha4 will be tagged in the next week or so and if no detrimental feedback is received over the next few weeks, both will get a stable tag before the end of November.

**Comment by roborourke** [comment] 2022-10-27 13:26
Quite the comeback for this issue! Great news, thanks @jrfnl

**Comment by jrfnl** [comment] 2022-12-09 15:00
In case you missed it: 1.0.0-RC1 has been tagged, 1.0.0 proper will be tagged in a week or two if no bugs have been reported.

**Comment by jrfnl** [comment] 2023-06-18 03:12
Oops.. forgot to close this issue. PHPCSExtra 1.0.0 was tagged beginning of January ;-)

**Closed as completed by jrfnl** 2023-06-18 03:12 UTC
Labels: Type: question
